# Site
title:              Lan(Lissie) Mei
bio:                'Lan is a focused MS in Business Analytics candidate at UC Davis, with relevant professional experience in digital marketing and customer analytics. Her previous experience at eBay, Nike and Converse have provided valuable insights into retailing and e-commerce.  She has proficient experience with SQL/NoSQL, R, Python, Stata, MS Office Suite, Tableau and Amazon Web Services (AWS), and is AWS Cloud Practitioner certified. She's keen to applying her skillsets and business acumen as a data analyst'
description:        " "
reading_time:       true
words_per_minute:   200
#logo:               'assets/img/profile.jpg'
logo:               'assets/img/22.jpg'
background:         'assets/img/tokyo-tower_.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://lmei33.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              lmei@ucdavis.edu
#twitter:            username
#facebook:           username
github-url:         lmei33
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          lan-mei
#xing:              username
#instagram:          messe.lissie
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
